name: potsoft_admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  google_fonts: ^3.0.1
  flutter_email_sender: ^5.2.0
  url_launcher: ^6.1.7
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
# F9:3D:1E:00:4F:CB:5C:9C:FF:0A:09:16:0D:99:18:0D:71:5C:C6:F3
# DB:C2:E9:FE:52:A1:D0:1A:E0:1F:6E:2C:46:8F:FA:1D:1F:0A:7E:73:ED:44:94:A1:A4:5A:83:70:FB:9B:9A:D7
